from plone.app.testing import TEST_USER_ID


'[{"unicode:field-data": {"utf8:IRelatedDocuments": {"utf8:relatedItems": []}, "utf8:ICreator": {"utf8:creators": []}, "utf8:IDocumentSchema": {"utf8:document_date": "utf8:2012-10-19", "utf8:delivery_date": null, "utf8:digitally_available": true, "utf8:preview": null, "utf8:description": null, "utf8:archival_file": null, "utf8:thumbnail": null, "utf8:receipt_date": null, "utf8:keywords": [], "utf8:document_type": null, "utf8:preserved_as_paper": true, "utf8:foreign_reference": null, "utf8:document_author": null, "utf8:file": {"utf8:filename": "unicode:test.txt", "utf8:data": "utf8:dGVzdCBibGEgYmxhCg==\n"}, "utf8:title": "unicode:test"}, "utf8:IClassification": {"utf8:privacy_layer": "unicode:privacy_layer_no", "utf8:public_trial": "unicode:unchecked", "utf8:public_trial_statement": "unicode:", "utf8:classification": "unicode:unprotected"}, "utf8:IVersionable": {"utf8:changeNote": "utf8:"}}, "utf8:basedata": {"utf8:id": "utf8:document-10", "utf8:portal_type": "utf8:opengever.document.document", "utf8:title": "utf8:test"}, "unicode:dublin-core": {"utf8:creator": "utf8:zopemaster", "utf8:created": "utf8:2012/10/19 15:57:30.879365 GMT+2"}, "unicode:intid-data": 389258091}]'


TASK_EXTRACTION = '{"unicode:field-data": {"utf8:ITask": {"utf8:deadline": "utf8:2012-10-24", "utf8:responsible_client": "unicode:plone", "utf8:effectiveCost": null, "utf8:effectiveDuration": null, "utf8:task_type": "utf8:approval", "utf8:text": null, "utf8:expectedCost": null, "utf8:responsible": "unicode:%s", "utf8:date_of_completion": null, "utf8:predecessor": null, "utf8:issuer": "unicode:testuser2", "utf8:expectedStartOfWork": null, "utf8:expectedDuration": null, "utf8:relatedItems": [], "utf8:title": "unicode:Testaufgabe"}}, "utf8:basedata": {"utf8:id": "utf8:task-1", "utf8:portal_type": "utf8:opengever.task.task", "utf8:title": "utf8:Testaufgabe"}, "unicode:dublin-core": {"utf8:creator": "utf8:zopemaster", "utf8:created": "utf8:2012/10/19 15:40:19.649945 GMT+2"}, "unicode:intid-data": 389258089}' %(TEST_USER_ID)


INBOX_EXTRACTION = '{"unicode:field-data": {"utf8:IForwarding": {"utf8:deadline": "utf8:2012-10-24", "utf8:responsible_client": "unicode:plone", "utf8:effectiveCost": null, "utf8:effectiveDuration": null, "utf8:task_type": "utf8:forwarding_task_type", "utf8:text": null, "utf8:expectedCost": null, "utf8:responsible": "unicode:inbox:plone", "utf8:date_of_completion": null, "utf8:predecessor": null, "utf8:issuer": "unicode:inbox:plone", "utf8:expectedStartOfWork": null, "utf8:expectedDuration": null, "utf8:relatedItems": [], "utf8:title": "unicode:Ein Testdokument"}}, "utf8:basedata": {"utf8:id": "utf8:forwarding-1", "utf8:portal_type": "utf8:opengever.inbox.forwarding", "utf8:title": "utf8:Ein Testdokument"}, "unicode:dublin-core": {"utf8:creator": "utf8:zopemaster", "utf8:created": "utf8:2012/10/19 15:58:8.235873 GMT+2"}, "unicode:intid-data": 389258092}'
