from opengever.ogds.models.declarative import query_base


UNIT_ID_LENGTH = 30
UNIT_TITLE_LENGTH = 255
GROUP_ID_LENGTH = 255
USER_ID_LENGTH = 255
FIRSTNAME_LENGTH = 255
LASTNAME_LENGTH = 255
EMAIL_LENGTH = 255
GROUP_TITLE_LENGTH = 255


BASE = query_base()
