.. py:class:: opengever.workspace.meetingagendaitem

    Inhaltstyp 'Traktandum'



   .. py:attribute:: title

       :Feldname: :field-title:`Titel`
       :Datentyp: ``TextLine``
       :Pflichtfeld: Ja :required:`(*)`
       
       
       


   .. py:attribute:: text

       :Feldname: :field-title:`Text`
       :Datentyp: ``RichText``
       
       
       
       


   .. py:attribute:: decision

       :Feldname: :field-title:`Decision`
       :Datentyp: ``RichText``
       
       
       
       


   .. py:attribute:: relatedItems

       :Feldname: :field-title:`Related items`
       :Datentyp: ``RelationList``
       
       :Default: []
       
       
