.. py:class:: opengever.inbox.inbox

    Inhaltstyp 'Eingangskorb'



   .. py:attribute:: inbox_group

       :Feldname: :field-title:`Eingangskorb Gruppe`
       :Datentyp: ``TextLine``
       
       
       :Beschreibung: Diese Gruppe wird berechtigt, wenn dem Eingangskorb eine Aufgabe zugewiesen wird.
       


   .. py:attribute:: changed

       :Feldname: :field-title:`Zuletzt verändert`
       :Datentyp: ``Datetime``
       
       
       
       


   .. py:attribute:: title_de

       :Feldname: :field-title:`Titel (deutsch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       


   .. py:attribute:: title_fr

       :Feldname: :field-title:`Titel (französisch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       


   .. py:attribute:: title_en

       :Feldname: :field-title:`Titel (englisch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       


   .. py:attribute:: responsible_org_unit

       :Feldname: :field-title:`Federführendes Amt`
       :Datentyp: ``TextLine``
       
       
       
       
