.. py:class:: opengever.private.root

    Inhaltstyp 'Persönliches Verzeichnis'



   .. py:attribute:: title_de

       :Feldname: :field-title:`Titel (deutsch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       


   .. py:attribute:: title_fr

       :Feldname: :field-title:`Titel (französisch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       


   .. py:attribute:: title_en

       :Feldname: :field-title:`Titel (englisch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       
