.. py:class:: opengever.repository.repositoryroot

    Inhaltstyp 'Ordnungssystem'



   .. py:attribute:: valid_from

       :Feldname: :field-title:`Gültig ab`
       :Datentyp: ``Date``
       
       
       
       


   .. py:attribute:: valid_until

       :Feldname: :field-title:`Gültig bis`
       :Datentyp: ``Date``
       
       
       
       


   .. py:attribute:: version

       :Feldname: :field-title:`Version`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: reference_number_addendum

       :Feldname: :field-title:`Aktenzeichen Zusatz`
       :Datentyp: ``TextLine``
       
       
       :Beschreibung: Achtung: Änderung erfordert Neuindexierung von "reference" und "sortable_reference".
       


   .. py:attribute:: title_de

       :Feldname: :field-title:`Titel (deutsch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       


   .. py:attribute:: title_fr

       :Feldname: :field-title:`Titel (französisch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       


   .. py:attribute:: title_en

       :Feldname: :field-title:`Titel (englisch)`
       :Datentyp: ``TranslatedTextLine``
       
       
       
       
