.. py:class:: opengever.repository.repositoryroot

    Inhaltstyp 'Ordnungssystem'



   .. py:attribute:: valid_from

       :Feldname: :field-title:`Gültig ab`
       :Datentyp: ``Date``
       
       
       
       


   .. py:attribute:: valid_until

       :Feldname: :field-title:`Gültig bis`
       :Datentyp: ``Date``
       
       
       
       


   .. py:attribute:: version

       :Feldname: :field-title:`Version`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: title_de

       :Feldname: :field-title:`Titel (deutsch)`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: title_fr

       :Feldname: :field-title:`Titel (französisch)`
       :Datentyp: ``TextLine``
       
       
       
       
