.. py:class:: opengever.contact.contact

    Inhaltstyp 'Kontakt'



   .. py:attribute:: salutation

       :Feldname: :field-title:`Anrede`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: academic_title

       :Feldname: :field-title:`Titel`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: lastname

       :Feldname: :field-title:`Nachname`
       :Datentyp: ``TextLine``
       :Pflichtfeld: Ja :required:`(*)`
       
       
       


   .. py:attribute:: firstname

       :Feldname: :field-title:`Vorname`
       :Datentyp: ``TextLine``
       :Pflichtfeld: Ja :required:`(*)`
       
       
       


   .. py:attribute:: company

       :Feldname: :field-title:`Firma`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: department

       :Feldname: :field-title:`Abteilung`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: function

       :Feldname: :field-title:`Funktion`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: email

       :Feldname: :field-title:`E-Mail 1`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: email2

       :Feldname: :field-title:`E-Mail 2`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: url

       :Feldname: :field-title:`URL`
       :Datentyp: ``URI``
       
       
       
       


   .. py:attribute:: phone_office

       :Feldname: :field-title:`Telefon Arbeit`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: phone_fax

       :Feldname: :field-title:`Fax Arbeit`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: phone_mobile

       :Feldname: :field-title:`Telefon Mobile`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: phone_home

       :Feldname: :field-title:`Telefon Privat`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: picture

       :Feldname: :field-title:`Bild`
       :Datentyp: ``NamedImage``
       
       
       
       


   .. py:attribute:: description

       :Feldname: :field-title:`Beschreibung`
       :Datentyp: ``Text``
       
       :Default: null
       
       


   .. py:attribute:: address1

       :Feldname: :field-title:`Adresse (Strasse / Nr.)`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: address2

       :Feldname: :field-title:`Adresszusatz`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: zip_code

       :Feldname: :field-title:`PLZ`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: city

       :Feldname: :field-title:`Ort`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: country

       :Feldname: :field-title:`Land`
       :Datentyp: ``TextLine``
       
       
       
       


   .. py:attribute:: changed

       :Feldname: :field-title:`Zuletzt verändert`
       :Datentyp: ``Datetime``
       
       
       
       
