#!/usr/local/bin/python
# -*- coding: utf-8 -*-
import re
import sys
import platform
from Zope2.Startup.zopectl import run
if __name__ == '__main__':
    # Call platform.uname() before registering any signal handlers
    # Fixes OSError: [Errno 10] No child processes
    # Related to: https://bugs.python.org/issue9127
    platform.uname()
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
