services:

  ianus-frontend:
    image: ghcr.io/4teamwork/ianus-frontend:${IANUS_VERSION:-latest}
    labels:
      - ch.onegovgever.client_id=${CLIENT_ID}
      - ch.onegovgever.hostname=${HOSTNAME:-localhost}
    ports:
      - "1${DEPLOYMENT_NUMBER}40:80"
    depends_on:
      - ianus-backend
    environment:
      - IANUS_BACKEND_HOST=ianus-backend
      - IANUS_PATH_PREFIX=/portal
    restart: always

  ianus-backend:
    image: ghcr.io/4teamwork/ianus-backend:${IANUS_VERSION:-latest}
    labels:
      - ch.onegovgever.client_id=${CLIENT_ID}
      - ch.onegovgever.hostname=${HOSTNAME:-localhost}
    environment:
      - BRANDING_THEME=${IANUS_BRANDING_THEME:-ogg}
      - DJANGO_SECRET_KEY=${IANUS_SECRET_KEY:-secret}
      - DJANGO_ALLOWED_HOSTS=${IANUS_ALLOWED_HOSTS:-localhost}
      - DJANGO_PATH_PREFIX=/portal
      - DJANGO_DATABASE_NAME=${IANUS_DATABASE_NAME:-ianus}
      - DJANGO_DATABASE_USER=${IANUS_DATABASE_USER:-ianus}
      - DJANGO_DATABASE_PASSWORD=${IANUS_DATABASE_PASSWORD:-secret}
      - DJANGO_DATABASE_HOST=${IANUS_DATABASE_HOST:-ianus-db}
      - DJANGO_DATABASE_PORT=${IANUS_DATABASE_PORT:-5432}
      - DJANGO_AUTH_LDAP_BIND_DN=${LDAP_BIND_DN}
      - DJANGO_AUTH_LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
      - DJANGO_AUTH_LDAP_SERVER_URI=${LDAP_SERVER_URI}
      - DJANGO_AUTH_LDAP_USER_BASE_DN=${LDAP_USER_BASE_DN}
      - DJANGO_AUTH_LDAP_USER_SEARCH_FILTER=${IANUS_AUTH_LDAP_USER_SEARCH_FILTER:-(uid=%(user)s)}
      - DJANGO_AUTH_LDAP_USER_OBJECTCLASS=${IANUS_AUTH_LDAP_USER_OBJECTCLASS:-top,person,organizationalPerson,inetUser,inetOrgPerson}
      - DJANGO_OIDC_RP_SIGN_ALGO=HS256
      - DJANGO_TWO_FACTOR_REQUIRED=${IANUS_TWO_FACTOR_REQUIRED:-False}
      - DJANGO_TWO_FACTOR_ENABLED=${IANUS_TWO_FACTOR_ENABLED:-True}
      - DJANGO_TWO_FACTOR_SETUP_ALLOWED=${IANUS_TWO_FACTOR_SETUP_ALLOWED:-True}
      - DJANGO_TWO_FACTOR_WHITELIST=${IANUS_TWO_FACTOR_WHITELIST:-127.0.0.1}
      - DJANGO_AUTH_LDAP_GROUP_BASE_DN=${LDAP_GROUP_BASE_DN}
      - DJANGO_AUTH_LDAP_GROUP_TYPE_CLASS=${IANUS_AUTH_LDAP_GROUP_TYPE_CLASS:-django_auth_ldap.config.GroupOfUniqueNamesType}
      - DJANGO_AUTH_LDAP_GROUP_MEMBER_ATTR=${IANUS_AUTH_LDAP_GROUP_MEMBER_ATTR:-uniqueMember}
      - DJANGO_AUTH_LDAP_GROUP_SEARCH_FILTER=${IANUS_AUTH_LDAP_GROUP_SEARCH_FILTER:-(objectClass=groupOfUniqueNames)}
      - DJANGO_AUTH_REGISTRATION_BACKEND=${IANUS_AUTH_REGISTRATION_BACKEND:-LDAPRegistrationBackend}
      - DJANGO_AUTH_REGISTRATION_GROUP_DN=${IANUS_AUTH_REGISTRATION_GROUP_DN:-}
      - DJANGO_AUTH_LDAP_USER_REGISTRATION_BASE_DN=${IANUS_AUTH_LDAP_USER_REGISTRATION_BASE_DN:-}
      - DJANGO_CAS_USER_ATTR_MAP=${IANUS_CAS_USER_ATTR_MAP:-{"email":"mail","firstname":"givenName","lastname":"sn","groups":"memberOf","full_name":"displayName"}}
      - DJANGO_ONBOARDING_ENABLED=${IANUS_ONBOARDING_ENABLED:-False}
      - DJANGO_CHANGE_PASSWORD_ENABLED=${IANUS_CHANGE_PASSWORD_ENABLED:-False}
      - DJANGO_RESET_PASSWORD_ENABLED=${IANUS_RESET_PASSWORD_ENABLED:-False}
      - DJANGO_DEFAULT_FROM_EMAIL=${IANUS_DEFAULT_FROM_EMAIL}
      - DJANGO_EMAIL_HOST=${SMTP_HOST:-localhost}
      - DJANGO_LDAP_MANAGE_USERS=${IANUS_LDAP_MANAGE_USERS:-False}
      - DJANGO_TWO_FACTOR_MANAGEMENT_ENABLED=${IANUS_TWO_FACTOR_MANAGEMENT_ENABLED:-False}
      - IANUS_INVITATION_SIGNATURE_SECRET_KEY=${WORKSPACE_SECRET:-}
    restart: always
