from zope.interface import Interface


class IFromTasktemplateGenerated(Interface):
    """Marker Interfaces for Task who are autmaticly generated by
    release a tasktemplate"""


class IFromSequentialTasktemplate(IFromTasktemplateGenerated):
    """Marker Interfaces for tasks who are autmaticly generated by
    triggering a sequential tasktemplatefolder"""


class IFromParallelTasktemplate(IFromTasktemplateGenerated):
    """Marker Interfaces for tasks who are autmaticly generated by
    triggering a parallel tasktemplatefolder"""


class IDuringTaskTemplateFolderTriggering(Interface):
    """Request marker present while generating tasks from a task template folder.
    """
