from zope.interface import Interface


class IFromTasktemplateGenerated(Interface):
    """Marker Interfaces for Task who are autmaticly generated by
    release a tasktemplate"""


class IDuringTaskTemplateFolderTriggering(Interface):
    """Request marker present while generating tasks from a task template folder.
    """
